name: The World of IT-Security
website: https://www.suresecure.de/aktuelles/podcast
podcastIndexID: 3790813
rssFeed: https://feeds.buzzsprout.com/1779426.rss
spotify: https://open.spotify.com/show/38ro5pDX7ToVMA9w6RVyNM
description: "IT-Security, unendliche Weiten ... So oder so ähnlich lässt sich die Größenordnung von alldem, was IT-Security betrifft, beschreiben - Netzwerk, Cloud, Endpoint, E-Mail, SOC, Schwachstellen, Sicherheitsvorfall, Awareness und vieeeles mehr. Klingt unfassbar kompliziert – ist aber auch unfassbar spannend. In unserem Podcast berichten wir über aktuelle Themen und zeigen euch, warum das Thema IT-Sicherheit auch für euren Alltag extrem wichtig ist. Denn das ist unsere Leidenschaft: eure Unternehmen und eure Arbeit sicher zu machen. Habt ihr heute schon auf einen Link geklickt? 😉"
tags:
  - Security
