name: Render README

on:
  workflow_dispatch:
  pull_request:

jobs:
  yaml:
    name: Render README
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-go@v5.0.1
        with:
          go-version: 1.22

      # Caching go modules to speed up the run
      - uses: actions/cache@v4.0.2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: make build

      - name: GermanTechPodcasts Convert JSON to README
        run: ./GermanTechPodcasts convertJsonToReadme --json-directory ../generated --readme-template ../assets/README.template --readme-output ../README.md
