name: YAML lint

on:
  push:
  workflow_dispatch:

jobs:
  yaml:
    name: YAML linting
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: podcasts/*.yml
