name: YAML lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  yaml:
    name: YAML linting
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3.5.2
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          file_or_dir: podcasts/*.yml
          config_file: .yamllint.yml
